name: Python CI

on:
  push:
    branches:
      - master

jobs:
  python-formatting-and-isort:
    runs-on: ubuntu-latest
    container:
      image: python:3.11.5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Auto-format code with black
        run: black api/*.py

      - name: Check and format the code with flake8
        run: flake8 api/*.py

  pyupgrade-check:
    needs: python-formatting-and-isort
    runs-on: ubuntu-latest
    container:
      image: python:3.11.5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install pyupgrade
        run: pip install pyupgrade

      - name: Check with pyupgrade
        run: pyupgrade --py3-plus api/*.py

  unit-test: 
    needs: pyupgrade-check
    runs-on: ubuntu-latest
    container:
      image: python:3.10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r requirements.txt
 
      - name: Run unit tests
        run: pytest api/*.py
  
  html-formatting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install html5validator
        run: pip install html5validator

      - name: Validate HTML
        run: python api/validator.py

  deploy-to-vercel:
    needs: [html-formatting, unit-test]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'
